services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - POSTGRES_DB=acme
      - POSTGRES_USER=acme
      - POSTGRES_PASSWORD=acme
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default
  # acme:
  #   build: .
  #   container_name: acme
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - default
  #   environment:
  #     - DB_HOST=localhost
  #     - DB_USER=acme
  #     - DB_PASSWORD=acme
  #     - AUTH_SECRET=FS0QpJJHztFfn+M99aUr7epssC1m0E8GUk1OMzuIkvI=
  #     - AUTH_TRUST_HOST=true

networks:
  default:
    name: acme

volumes:
  postgres-data:
