services:
  database:
    image: 'mysql:latest'
    container_name: database
    environment:
      - MYSQL_DATABASE=acme
      - MYSQL_ROOT_PASSWORD=acme
      - MYSQL_USER=acme
      - MYSQL_PASSWORD=acme
    ports:
      - "3306:3306"
    networks:
      - default
  acme:
    build: .
    container_name: acme
    ports:
      - "3000:3000"
    networks:
      - default
    environment:
      - DB_URL=mysql://root:acme@database/acme
      - DB_HOST=localhost
      - DB_USER=acme
      - DB_PASSWORD=acme
      - DB_NAME=acme
      - AUTH_SECRET=FS0QpJJHztFfn+M99aUr7epssC1m0E8GUk1OMzuIkvI=

networks:
  default:
