apiVersion: v1
kind: Secret
metadata:
  name: application-secrets
type: Opaque
data:
  NEXTAUTH_URL: "aHR0cDovLzE5Mi4xNjguMTgxLjEyODozMDA4MC9hcGkvYXV0aC9zZXNzaW9u"
  AUTH_TRUST_HOST: "aHR0cDovLzE5Mi4xNjguMTgxLjEyODozMDA4MA=="
  AUTH_SECRET: "RlMwUXBKSkh6dEZmbitNOTlhVXI3ZXBzc0MxbTBFOEdVazFPTXp1SWt2ST0="
  DB_HOST: "ZGF0YWJhc2Utc2VydmljZQ=="
  DB_NAME: "YWNtZQ=="
  DB_USER: "cm9vdA=="
  DB_PASSWORD: "YWNtZQ=="
  DB_URL: "bXlzcWw6Ly9yb290OmFjbWVAZGF0YWJhc2Utc2VydmljZS9hY21l"
