apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: gabreel05/acme-application:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: AUTH_SECRET
              key: AUTH_SECRET 
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: DB_HOST
              key: DB_HOST 
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: DB_NAME
              key: DB_NAME 
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: DB_USER
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: DB_PASSWORD
              key: DB_PASSWORD
