apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-data"
