apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: gabreel05/acme-database:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: MYSQL_DATABASE 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: MYSQL_ROOT_PASSWORD 
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: MYSQL_USER 
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: database-storage
          mountPath: /var/lib/acme-database
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: database-pvc
