apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pvc
spec:
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-data"
